name: extended_image
description: Official extension image, support placeholder(loading)/ failed state, cache network, zoom/pan, photo view, slide out page, editor(crop,rotate,flip), painting etc.
version: 4.1.0
homepage: https://github.com/fluttercandies/extended_image

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  extended_image_library:
      git:
        url: git://github.com/telahng/extended_image_library.git
        ref: master
  flutter:
    sdk: flutter
  meta: ^1.1.8

